CC=g++
CPPFLAGS=-Wall -O0 -std=c++11 -ggdb

2.2.2:
	g++ 2.2.2.cc -O0 -std=c++11 -ggdb -o 2.2.2
4.5:
	g++ 4.5.cc -O0 -std=c++11 -ggdb -o 4.5
6:
	g++ 6.cc -O0 -std=c++11 -Wall -ggdb -o 6
9:
	g++ 9.cc -O0 -std=c++11 -Wall -ggdb -o 9
grep:
	g++ grep.cc -O0 -std=c++11 -Wall -ggdb -o grep -lpthread
teststack:
	g++ teststack.cc -O0 -std=c++11 -Wall -ggdb -o teststack -lpthread
ngrep:
	g++ ngrep.cc -O0 -std=c++11 -Wall -ggdb -o ngrep -lpthread
